# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('post', 'Post'), ('intro', 'Introduction'), ('pinned_post', 'Pinned Post'), ('draft', 'Draft')], default='draft', max_length=100),
        ),
    ]
