# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171004_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author'),
        ),
    ]
