# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171004_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
